#include "../cfgdefault/CFG_Custom1_Default.h"
#include "../cfgdefault/CFG_GPS_Default.h"
#include "../cfgdefault/CFG_PRODUCT_INFO_Default.h"
#include "../cfgdefault/CFG_WIFI_Default.h"
#include "../cfgdefault/CFG_ACER_NUMBER_Default.h"
#include "../cfgdefault/CFG_ACER_NUMBER_SNID_Default.h"
#include "../cfgdefault/CFG_CCI_SW_Default.h"
#include "../cfgdefault/CFG_Warranty_Default.h"
#include "../cfgdefault/CFG_P_SENSOR_THRESHOLD_Default.h"

